parameters:
  jobName: ''
  moduleName: ''
  artifactName: ''

jobs:
  # build owlcms uberjar and zip to be used by installer
  - job: ${{ parameters.jobName }}
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: steps-prepare-maven.yml
      - task: Maven@3
        displayName: build owlcms uberJar and deploy to bintray
        inputs:
          mavenPomFile: pom.xml
          mavenOptions: -Xmx3072m $(MavenOpts)
          javaHomeOption: JDKVersion
          jdkVersionOption: "1.8"
          jdkArchitectureOption: x64
          publishJUnitResults: true
          testResultsFiles: "**/surefire-reports/TEST-*.xml"
          goals: -P production -pl ${{ parameters.moduleName }} -am $(MavenOpts) -Dmaven.test.skip=true $(BuildGoal)
      - publish: $(Agent.BuildDirectory)/s/${{ parameters.moduleName }}/target/${{ parameters.moduleName }}.zip
        artifact: ${{ parameters.artifactName }}
