steps:
-  checkout: self
   submodules: recursive
-  task: MavenAuthenticate@0
   displayName: Populate settings.xml servers
   inputs:
      mavenServiceConnections: bintray-owlcms-maven
-  task: Cache@2
   displayName: Cache Maven local repository
   inputs:
      key: maven | "$(Agent.OS)" | 1
      restoreKeys: |
         maven | "$(Agent.OS)"
         maven
      path: $(MavenCacheFolder)